name: Juno
options:
  bundleIdPrefix: com.example
settings:
  base:
    MACOSX_DEPLOYMENT_TARGET: 13.0
    SWIFT_VERSION: 5.0

targets:
  Juno:
    type: application
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - Sources
    info:
      path: Sources/Info.plist
      properties:
        CFBundleDisplayName: Juno
        LSUIElement: true
